# Generated by Django 3.1.5 on 2021-02-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_auto_20210130_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Downvote',
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
